//! Counting Atlas, so no document has to.
//!
//! Ten documents in `docs/` each state a test count. They were all correct on
//! the day they were written and none of them are correct now. The fix is not
//! discipline, it is removing the opportunity: numbers live here, prose links
//! to them, and `atlas metrics` regenerates the block.
//!
//! Deliberately dependency-free and deliberately approximate about lines of
//! code — the point is drift detection, not accountancy.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Metrics {
    pub modules: usize,
    pub src_lines: usize,
    pub test_files: usize,
    pub test_lines: usize,
    pub test_fns: usize,
    pub config_lines: usize,
    pub dependencies: usize,
    /// Modules nothing in the running program can reach.
    pub unwired: Vec<String>,
}

fn rs_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = fs::read_dir(dir) else {
        return out;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            out.extend(rs_files(&p));
        } else if p.extension().and_then(|x| x.to_str()) == Some("rs") {
            out.push(p);
        }
    }
    out.sort();
    out
}

fn count_lines(paths: &[PathBuf]) -> usize {
    paths
        .iter()
        .filter_map(|p| fs::read_to_string(p).ok())
        .map(|t| t.lines().count())
        .sum()
}

/// Gather the numbers from a repo root.
///
/// `unwired` is supplied by the caller rather than recomputed here, because
/// the reachability walk lives in `tests/wiring.rs` where it can fail a build.
/// Duplicating it would give two sources of truth for the one fact this module
/// exists to stop duplicating.
pub fn gather(root: &Path, unwired: Vec<String>) -> Metrics {
    let src = root.join("src");
    let tests = root.join("tests");
    let config = root.join("config");

    let src_files = rs_files(&src);
    // One module per top-level file, plus one for the platform directory.
    // Counting `platform/{mod,win,mock}.rs` separately would inflate the
    // figure and make it disagree with `lib.rs`, which is the number people
    // actually mean when they say "modules".
    let mut modules = src_files
        .iter()
        .filter(|p| p.parent() == Some(src.as_path()))
        .filter(|p| {
            let stem = p.file_stem().and_then(|s| s.to_str()).unwrap_or("");
            !matches!(stem, "lib" | "main")
        })
        .count();
    if src.join("platform").is_dir() {
        modules += 1;
    }

    let test_files_v = rs_files(&tests);
    let test_fns = test_files_v
        .iter()
        .filter_map(|p| fs::read_to_string(p).ok())
        .map(|t| t.matches("#[test]").count())
        .sum();

    let config_lines = fs::read_dir(&config)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|e| {
            e.path().extension().and_then(|x| x.to_str()) == Some("yaml")
        })
        .filter_map(|e| fs::read_to_string(e.path()).ok())
        .map(|t| t.lines().count())
        .sum();

    let dependencies = fs::read_to_string(root.join("Cargo.toml"))
        .map(|t| {
            let mut names = BTreeSet::new();
            let mut in_deps = false;
            for line in t.lines() {
                let l = line.trim();
                if l.starts_with('[') {
                    in_deps = l.contains("dependencies");
                    continue;
                }
                // Only `name = ...` lines. Feature lists inside a dependency
                // table are continuation lines and must not be counted as
                // separate crates.
                if in_deps && !l.is_empty() && !l.starts_with('#') && !l.starts_with('"') {
                    if let Some((name, _)) = l.split_once('=') {
                        let name = name.trim();
                        if !name.is_empty() && !name.contains(' ') {
                            names.insert(name.to_string());
                        }
                    }
                }
            }
            names.len()
        })
        .unwrap_or(0);

    Metrics {
        modules,
        src_lines: count_lines(&src_files),
        test_files: test_files_v.len(),
        test_lines: count_lines(&test_files_v),
        test_fns,
        config_lines,
        dependencies,
        unwired,
    }
}

impl Metrics {
    /// The block to paste into docs, or write to `docs/METRICS.md`.
    pub fn render(&self) -> String {
        let mut s = String::new();
        s.push_str("# Atlas by the numbers\n\n");
        s.push_str("*Generated by `atlas metrics`. Do not edit by hand, and do not\n");
        s.push_str("restate these figures anywhere else — link here instead.*\n\n");
        s.push_str(&format!("| modules | {} |\n", self.modules));
        s.push_str("|---|---|\n");
        s.push_str(&format!("| lines of source | {} |\n", self.src_lines));
        s.push_str(&format!("| test files | {} |\n", self.test_files));
        s.push_str(&format!("| lines of test | {} |\n", self.test_lines));
        s.push_str(&format!("| tests | {} |\n", self.test_fns));
        s.push_str(&format!("| lines of config | {} |\n", self.config_lines));
        s.push_str(&format!("| dependencies | {} |\n", self.dependencies));
        s.push_str(&format!("| modules not yet wired in | {} |\n", self.unwired.len()));

        if self.unwired.is_empty() {
            s.push_str("\nEvery module is reachable from the entrypoint.\n");
        } else {
            s.push_str("\n## Written but not reachable\n\n");
            s.push_str("These compile and are tested. Nothing in the running program\n");
            s.push_str("can call them. `tests/wiring.rs` holds the list as a ratchet.\n\n");
            for m in &self.unwired {
                s.push_str(&format!("- `{m}`\n"));
            }
        }
        s
    }
}
